"""
Django settings for hmship project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1st2=_h5tee^+a*0=x)%ee$31)b$hxoal!&ao57wxz!@(p&5)t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']



#PROJECT EMAIL SETTINGS
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'peto813@gmail.com'
# EMAIL_HOST_PASSWORD = 'ou63ut14#'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = 'webmaster@condominioaldia.net'


LOGISTICS_EMAIL = ['peto813@gmail.com']
MAINTENANCE_EMAIL = ['peto813@gmail.com']
SERVICE_EMAIL = ['peto813@gmail.com']
ADMINISTRATIVE_EMAIL = ['peto813@gmail.com']
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
ADMINS = (('Frank Albornoz', 'peto813@gmail.com'), ('Einstein Millan', 'peto813@hotmail.com'))
# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'grappelli.dashboard',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userapp.apps.UserappConfig',
    'rest_framework',
    #'rest_auth'
    # The Django sites framework is required for allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_auth.registration',
    'rest_framework.authtoken',
    'django_filters',
    # ... include the providers you want to enable:
    # 'allauth.socialaccount.providers.amazon',
    # 'allauth.socialaccount.providers.angellist',
    # 'allauth.socialaccount.providers.asana',
    # 'allauth.socialaccount.providers.baidu',
    # 'allauth.socialaccount.providers.basecamp',
    # 'allauth.socialaccount.providers.bitbucket',
    # 'allauth.socialaccount.providers.bitbucket_oauth2',
    # 'allauth.socialaccount.providers.bitly',
    # 'allauth.socialaccount.providers.coinbase',
    # 'allauth.socialaccount.providers.digitalocean',
    # 'allauth.socialaccount.providers.discord',
    # 'allauth.socialaccount.providers.douban',
    # 'allauth.socialaccount.providers.draugiem',
    # 'allauth.socialaccount.providers.dropbox',
    # 'allauth.socialaccount.providers.dropbox_oauth2',
    # 'allauth.socialaccount.providers.edmodo',
    # 'allauth.socialaccount.providers.eveonline',
    # 'allauth.socialaccount.providers.evernote',
    'allauth.socialaccount.providers.facebook',
    # 'allauth.socialaccount.providers.feedly',
    # 'allauth.socialaccount.providers.fivehundredpx',
    # 'allauth.socialaccount.providers.flickr',
    # 'allauth.socialaccount.providers.foursquare',
    # 'allauth.socialaccount.providers.fxa',
    # 'allauth.socialaccount.providers.github',
    # 'allauth.socialaccount.providers.gitlab',
    'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.hubic',
    #'allauth.socialaccount.providers.instagram',
    # 'allauth.socialaccount.providers.linkedin',
    # 'allauth.socialaccount.providers.linkedin_oauth2',
    # 'allauth.socialaccount.providers.mailru',
    # 'allauth.socialaccount.providers.odnoklassniki',
    # 'allauth.socialaccount.providers.openid',
    # 'allauth.socialaccount.providers.orcid',
    # 'allauth.socialaccount.providers.paypal',
    # 'allauth.socialaccount.providers.persona',
    # 'allauth.socialaccount.providers.pinterest',
    # 'allauth.socialaccount.providers.reddit',
    # 'allauth.socialaccount.providers.robinhood',
    # 'allauth.socialaccount.providers.shopify',
    # 'allauth.socialaccount.providers.slack',
    # 'allauth.socialaccount.providers.soundcloud',
    # 'allauth.socialaccount.providers.spotify',
    # 'allauth.socialaccount.providers.stackexchange',
    # 'allauth.socialaccount.providers.stripe',
    # 'allauth.socialaccount.providers.tumblr',
    # 'allauth.socialaccount.providers.twentythreeandme',
    # 'allauth.socialaccount.providers.twitch',
    'allauth.socialaccount.providers.twitter',
    # 'allauth.socialaccount.providers.untappd',
    # 'allauth.socialaccount.providers.vimeo',
    # 'allauth.socialaccount.providers.vk',
    # 'allauth.socialaccount.providers.weibo',
    # 'allauth.socialaccount.providers.weixin',
    # 'allauth.socialaccount.providers.windowslive',
    # 'allauth.socialaccount.providers.xing',
]

GRAPPELLI_INDEX_DASHBOARD = 'dashboard.CustomIndexDashboard'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
  
    ),
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # 'DEFAULT_PARSER_CLASSES': (
    #     'rest_framework.parsers.JSONParser',
    # ),
    'DEFAULT_RENDERER_CLASSES' : (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        #'rest_framework.permissions.DjangoModelPermissions'
        #'rest_framework.permissions.IsAuthenticatedOrReadOnly',
        #'rest_framework.permissions.IsAuthenticated'
        'rest_framework.permissions.AllowAny'

    ]
}

MIDDLEWARE = [
    #'userapp.middleware.SimpleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]


AUTHENTICATION_BACKENDS = (

    # Needed to login by username in Django admin, regardless of `allauth`
    #'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)


ROOT_URLCONF = 'hmship.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [os.path.join(BASE_DIR, 'templates'), 
                os.path.join(BASE_DIR, 'templates', 'userapp')
                # os.path.join(BASE_DIR, 'templates', 'userapp', 'sharedcomponents', 'navbar')
                # os.path.join(BASE_DIR, 'templates', 'account'),
                #os.path.join(BASE_DIR, 'templates', 'usuario'),
                #os.path.join(BASE_DIR, 'templates', 'forms'), # REGISTRATION FORMS TEMPLATES DIRECTORY
                #os.path.join(BASE_DIR, 'templates', 'usuario', 'condominios'), #CONDOMINIOS FINANCIAL TEMPLATES
                #os.path.join(BASE_DIR, 'templates', 'usuario', 'propietarios'), #CONDOMINIOS FINANCIAL TEMPLATES
                #os.path.join(BASE_DIR, 'templates', 'usuario', 'pdfTemplates'),
                #os.path.join(BASE_DIR, 'templates', 'admin', 'usuario'),
                #os.path.join(BASE_DIR, 'templates', 'markdown'),
                #os.path.join(BASE_DIR, 'templates', 'usuario', 'email')
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'django.core.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'hmship.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases


#AUTH_USER_MODEL = 'models.Custom_User'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hmshipdb',
        'USER': 'root',
        'PASSWORD': 'ou63ut14',
        'HOST': '127.0.0.1',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators



# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT=os.path.join(BASE_DIR, "static", "static_root")

        #The absolute path to the directory where collectstatic will collect static files for deployment.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static", "mystatic"), #this is where images, js and css go
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media_root")
# these two have to do with end-users (whatever is being uploaded) 



# ALLAUTH SETTINGS

SOCIALACCOUNT_FORMS = {
    'signup': 'hmship.userapp.forms.CustomSocialSignupForm'
}

SITE_ID = 1

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGIN_REDIRECT_URL = '/'


# REST AUTH/ALLAUTH CONFIGURATION
#LOGIN_REDIRECT_URL='/'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
#setting this to mandatory forces 
#ACCOUNT_EMAIL_VERIFICATION =  'mandatory'

#SOCIAL APP SETTINGS
FACEBOOK_APP_ID = '1298298486913255'

#TWITTER SOCIAL APP SETTINGS OAUTH AUTHENTICATION
OAUTH_TOKEN = ""
OAUTH_TOKEN_SECRET = ""
CONSUMER_KEY = 'lZvNYlhXR59lVc9g5aTGnrYp5'
CONSUMER_SECRET = 'ZmLZShTJ0JG2Jr0zEt6f9qrWv4NyrJXmi3o0GRGlGh44h0ugwj'
OAUTH_TOKEN = '849744432018706432-uwig6uFPi8yHOdgvJCifavAjJvFMGFS'
OAUTH_TOKEN_SECRET = 'bYQS7HLwxljl8DMQFhDBOT32INRsJUtTRPnJhdNDlKp4b'

REQUEST_TOKEN_URL = "https://api.twitter.com/oauth/request_token"
AUTHORIZE_URL = "https://api.twitter.com/oauth/authorize?oauth_token="
ACCESS_TOKEN_URL = "https://api.twitter.com/oauth/access_token"

#PAYPAL SETTINGS
PAYPAL_CLIENT_ID = 'AeUZx0X4XylAQXl4oHVHi-dO1CBr_O9psjrz3B_OeDQ-penTIoRtxGI8q2222ThuUQ2A1c0AeLUiWtlz'
PAYPAL_CLIENT_SECRET = 'EKpXjjzjIly0M2njfsA8pM6Lh4k9Lf5lljZL2Ywema3id8fVGErgcytK-jOxfSbQMIriaa9BTl_UNSkf'
#DEFAULT_FILTER_BACKENDS = 'DjangoFilterBackend'